### ISSUE TITLE
Comprehend and integrate with (part of) the Node-To-Node protocol to submit transactions

### ISSUE THREAD

**Issue by commandodev** [input-output-hk/cardano-wallet-legacy#10]
# Context

<What is the issue that we are seeing that is motivating this decision or
change. Give any elements that help understanding where this issue comes from.
Leave no room for suggestions or implicit deduction.>

Being a node, the Wallet "shortcuts" the transaction submission by directly pushing transactions
to the node's queue. In order to fully decouple the wallet, we would need the wallet to use
the Node <-> Node protocol in order to submit transactions. 

# Decision

<Give details about the architectural decision and what it is doing. Be
extensive: use schemas and references when possible. Do not hesitate to use
schemas and references when possible.>

Before taking any further action, we want to comprehend and document the relevant parts of the Node-To-Node protocol that is used to submit transactions. A few areas to start looking at are located in the `chain` and `networking` packages from `cardano-sl`. 

# Acceptance Criteria

<Use standard vocabulary to describe requirement levels RFC-2119: Must-Should-May.
e.g.: The API _must_ support creation of wallets through a dedicated endpoint.>

1. - [x] We _must_ understand and document relevant bits of the Node-To-Node Protocol.
1. - [x] We _must_ distinguish clearly what is transmitted "over-the-wire" from what is just plain shared Haskell structures.

# PR

https://github.com/input-output-hk/cardano-wallet/wiki/Submitting-Transaction-Byron

---

# Consequences

The wallet component comes with diffusion layer component and we want to continue with this. Diffusion layer component takes care of submitting transaction using infra and network primitives and disseminate it to the peers. We understand it fully and even when `ouroboros-network` people introduce something new we expect they adapt the diffusion layer with their new developments an we are still happy.

**Comment by paweljakubas** [comment]
Detailed description how transaction is shared among peers using diffusion layer conversational protocol is added : https://github.com/input-output-hk/cardano-wallet/wiki/Submitting-Transaction-Before

**Comment by commandodev** [comment]
That's a really great spec @paweljakubas!
