### ISSUE TITLE
Clearly identify current areas where transactions are submitted / resubmitted

### ISSUE THREAD

**Issue by commandodev** [input-output-hk/cardano-wallet-legacy#11]
# Context

<What is the issue that we are seeing that is motivating this decision or
change. Give any elements that help understanding where this issue comes from.
Leave no room for suggestions or implicit deduction.>

The wallet has gone through quite a lot of changes recently with the introduction of the new data-layer. This includes some reshuffling in the way transactions are submitted. 

# Decision

<Give details about the architectural decision and what it is doing. Be
extensive: use schemas and references when possible. Do not hesitate to use
schemas and references when possible.>

We want to identify and document (as a wiki page) the process of submitting transactions in a cardano-wallet. This could come with schemas, code excerpt and prose to give as many details as possible.

# Acceptance Criteria

<Use standard vocabulary to describe requirement levels RFC-2119: Must-Should-May.
e.g.: The API _must_ support creation of wallets through a dedicated endpoint.>

1. - [x] We _must_ clearly identify and document how transactions are currently submitted to the node
2. - [x] We _must_ identify the remaining steps for the wallet to achieve full decoupling regarding submission.

# Wiki

- https://github.com/input-output-hk/cardano-wallet/wiki/Submitting-Transaction-Before

---

# Consequences

The wallet uses its internal diffusion layer as an intermediary to submit transaction to the diffusion layer component. As the wallet and diffusion layer components are stitched together, and plan to be that way in the future, we are happy with how it works

**Comment by paweljakubas** [comment]
https://github.com/input-output-hk/cardano-wallet/wiki/Submitting-Transaction-Before
