### ISSUE TITLE
Abstract Away Submission of Transactions

### ISSUE THREAD

**Issue by commandodev** [input-output-hk/cardano-wallet-legacy#12]
# Context

<What is the issue that we are seeing that is motivating this decision or
change. Give any elements that help understanding where this issue comes from.
Leave no room for suggestions or implicit deduction.>

See outcomes from #10 and #11  

# Decision

<Give details about the architectural decision and what it is doing. Be
extensive: use schemas and references when possible. Do not hesitate to use
schemas and references when possible.>

FIXME: Complete this decision once #10 & #11 have been resolved.

# Acceptance Criteria

<Use standard vocabulary to describe requirement levels RFC-2119: Must-Should-May.
e.g.: The API _must_ support creation of wallets through a dedicated endpoint.>

1. - [ ] Bits related to submission of transaction _must_ be abstracted in a protocol-neutral interface.
1. - [ ] The interface from #12.1 _mustn't_ expose any protocol related parameters.
1. - [ ] It _must_ be possible to emulate the interface from #12.1 using the existing code.
1. - [ ] An implementation of #12.3 _may_ be provided as an illustration.

# PR

| Number    | Base      |
| ---       | ---       |
| [][PR-1] | `develop` |

[PR-1]: https://github.com/input-output-hk/cardano-wallet/pull/ 

---

# Consequences

<To be completed in retrospective. What becomes easier or more difficult to do
because of this change.>

**Comment by KtorZ** [comment]
This is already abstracted away through the diffusion layer which sends transaction over the wire.
