### ISSUE TITLE
`spendingPasswordLastUpdate` not updated correctly upon setting empty spending password (PUT /api/v1/wallets/{walletId}/password)

### ISSUE THREAD

**Issue by piotr-iohk** [input-output-hk/cardano-wallet-legacy#166]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux | Code |

# Context
 
`spendingPasswordLastUpdate` is one of the fields available on `/api/v1/wallets` endpoint (for example for `GET /api/v1/wallets/{walletId}`). The fleld should present datetime of the last spending password update. The problem is that when updating password to empty ("") this field is not updated accordingly. In fact, it is then set to the wallet create date -> `createdAt`.

# Steps to Reproduce

1. create wallet:
```
curl  -X POST https://localhost:8090/api/v1/wallets \
  -H "Accept: application/json; charset=utf-8" \
  -H "Content-Type: application/json; charset=utf-8" \
  --cert ~/.local/share/Daedalus/staging/tls/client/client.pem \
  --cacert ~/.local/share/Daedalus/staging/tls/client/ca.crt \
  -d '{
  "operation": "create",
  "backupPhrase":["door", "pigeon", "vivid", "address", "slim", "catalog", "thumb", "hollow", "talk", "kiss", "system", "spawn"],
  "assuranceLevel": "normal",
  "name": "test_spending_pass",
  "spendingPassword": "5416b2988745725998907addf4613c9b0764f04959030e1b81c603b920a115d0"
}'  
```
2. Invoke `GET /api/v1/wallets/{walletId}` and record value  of `spendingPasswordLastUpdate` (e.g. "spendingPasswordLastUpdate": "2018-12-17T13:08:34.904758",)
```
curl -X GET https://localhost:8090/api/v1/wallets/Ae2tdPwUPEZCqhaMLiQsNcF3AiwS31YL2HADYvDry4aWJXFk3hRZLjuDAUk \
  -H "Accept: application/json; charset=utf-8" \
  -H "Content-Type: application/json; charset=utf-8" \
  --cert ~/.local/share/Daedalus/staging/tls/client/client.pem \
  --cacert ~/.local/share/Daedalus/staging/tls/client/ca.crt
```
3. Set spending password to ""

```
curl -X PUT https://localhost:8090/api/v1/wallets/Ae2tdPwUPEZCqhaMLiQsNcF3AiwS31YL2HADYvDry4aWJXFk3hRZLjuDAUk/password\
  -H "Accept: application/json; charset=utf-8" \
  -H "Content-Type: application/json; charset=utf-8" \
  --cert ~/.local/share/Daedalus/staging/tls/client/client.pem \
  --cacert ~/.local/share/Daedalus/staging/tls/client/ca.crt \
  -d '{
  "old": "5416b2988745725998907addf4613c9b0764f04959030e1b81c603b920a115d0",
  "new": ""
}' 
```
4. Invoke `GET /api/v1/wallets/{walletId}` to see the value of `spendingPasswordLastUpdate`

## Expected behavior
`spendingPasswordLastUpdate` should be updated with recent datetime.

## Actual behavior
 
`spendingPasswordLastUpdate` is updated to the same date that is under `createdAt`.

**Note:** It may be related to this piece -> https://github.com/input-output-hk/cardano-wallet/blob/develop/src/Cardano/Wallet/Kernel/Wallets.hs#L484-L485

---

# Resolution Plan

## The reason

1. If spending password set to an empty string, wallet has `NoSpendingPassword` mode: https://github.com/input-output-hk/cardano-wallet/blob/develop/src/Cardano/Wallet/Kernel/Wallets.hs#L475-L476
2. We have a converter, where last update date is setting up: https://github.com/input-output-hk/cardano-wallet/blob/develop/src/Cardano/Wallet/WalletLayer/Kernel/Conv.hs#L167
3. And if this wallet corresponds to `NoSpendingPassword` (because of empty spending password), `mbLastUpdate` becomes `Nothing`: https://github.com/input-output-hk/cardano-wallet/blob/develop/src/Cardano/Wallet/WalletLayer/Kernel/Conv.hs#L177-L179. So, if it's `Nothing`, then here (https://github.com/input-output-hk/cardano-wallet/blob/develop/src/Cardano/Wallet/WalletLayer/Kernel/Conv.hs#L185) `lastUpdate` becomes `createdAt`.

The problem is in https://github.com/input-output-hk/cardano-wallet/blob/develop/src/Cardano/Wallet/WalletLayer/Kernel/Conv.hs#L185: even if user sets spending password as an empty string - yes, wallet is in `NoSpendingPassword` mode now, bit it _is_ an update, so it should be marked by this actual time, not by creation time. The reason of this problem is here: https://github.com/input-output-hk/cardano-wallet/blob/develop/src/Cardano/Wallet/Kernel/Wallets.hs#L476: we just discard `lastUpdateNow` because of `HasSpendingPassword` type (https://github.com/input-output-hk/cardano-wallet/blob/develop/src/Cardano/Wallet/Kernel/DB/HdWallet.hs#L187-L192).

## The plan to solve

- [x] Type `HasSpendingPassword` should be extended: constructor `NoSpendingPassword` should have `InDb Core.Timestamp` as well as `HasSpendingPassword` constructor.
- [x] By default `NoSpendingPassword` constructor contains `createdAt` value. But if user sets spending password to an empty string (i.e. removes spending password), which is checked here (https://github.com/input-output-hk/cardano-wallet/blob/develop/src/Cardano/Wallet/Kernel/Wallets.hs#L475-L476) - time of this update (which is `lastUpdateNow` from https://github.com/input-output-hk/cardano-wallet/blob/develop/src/Cardano/Wallet/Kernel/Wallets.hs#L469) should be stored here: https://github.com/input-output-hk/cardano-wallet/blob/develop/src/Cardano/Wallet/Kernel/Wallets.hs#L476.

# PR

| Number   | Base      |
| ---      | ---       |
| #201       | `develop` |
| #211       | `develop` |

# QA 

Integration test was added (please see https://github.com/input-output-hk/cardano-wallet/pull/211). It corresponds to `WALLETS_UPDATE_PASS_04` scenario.

**Comment by piotr-iohk** [comment]
Hey @denisshevchenko , there is no QA section filled for this ticket... 
I would suggest also adding an integration test for the scenario from the bug. Actually it is even mentioned as one of the capabilities in the https://docs.google.com/spreadsheets/d/1ztF2PnnrMnkAxrhdq3LUbP1KazxcxuMrbiObTs1CuTk (WALLETS_UPDATE_PASS_04 - Updating password updates date in 'spendingPasswordLastUpdate'), so if you would add it as part of this bug resolution it would be great! :) We would then have two birds killed with one stone (part of the req covered and actual automated retest for the bug)

**Comment by denisshevchenko** [comment]
@piotr-iohk It's done: https://github.com/input-output-hk/cardano-wallet/pull/211

**Comment by piotr-iohk** [comment]
Looks great! :) Just one minor change needed in the scenario title to be inline with the requirement spreadsheet (added a comment to the PR #211).
