### ISSUE TITLE
Add golden tests for bip44 derivations

### ISSUE THREAD

**Issue by akegalj** [input-output-hk/cardano-wallet-legacy#195]
# Context

In #41 we have implemented bip44 derivations and added property tests. Nicolas advised to use `cardano-cli` to generate golden tests for bip32/bip44 and add module for bip44ed255915 golden tests:
 * Nicolas advised to use rust's cardano-cli to generate golden tests https://github.com/input-output-hk/cardano-cli, https://cardanorust.iohkdev.io/cli-wallet/
 * use cardano-cli instructions https://github.com/input-output-hk/cardano-wallet/wiki/Testing-Yoroi-and-Cardano-wallet

# Decision

Add golden tests for bip44 derivations defined in #41. 

# Acceptance Criterias

1. Tests _must_ contain golden test for deriving public key from private key
2. Tests _must_ contain golden test for deriving account private key from master private key
3. Tests _must_ contain golden test for deriving address private key from account private key
4. Tests _must_ contain golden test for deriving address public key from account public key
5. Issue _should_ add tutorial about how to use `cardano-cli` to add golden tests as `cardano-wallet` wiki page

---

# Development Plan

- [x] I intend to extend `cardano-sl/mnemonic` package to support new seed generation as done by Icarus/Yoroi.

- [x] I intend to add support for passphrase 

- [x] I intend to add golden test in cardano-wallet to compare addresses generated from `cardano-cli` and the one obtained from `cardano-wallet` using the same set of mnemonic and password

- [x] I intend to extend the wiki documentation to explain how to generate new test vectors

# PR

| Number   | Base      |
| ---      | ---       |
| #227        | `develop` |

# QA 

| Criteria | Coverage |
| ---      | ---      |
| 1, 2, 3, 4 | I've taken a slightly different approach here and went for [golden test comparing the whole address](https://github.com/input-output-hk/cardano-wallet/blob/417853293e618c5bc09b0b2036c83b10afe616a3/test/unit/Golden/Ed25519Addresses.hs#L40-L68). Reasons a plural: <br/> 1/ We can compare them against addresses generated via `cardano-cli`, <br/> 2/ We don't have access to intermediate byte representations on `cardano-cli` (without instrumenting the rust code via debug and println and recompiling it locally, which is sort-of impractical) <br/> 3/ It achieves the same end-goal for if intermediate representations don't match, then the final address won't either. <br/> 4/ Tests are also quite easy to read and extend this way. 
| 5        | I've added a corresponding section to the [Testting Yoroi and Cardano Wallet](https://github.com/input-output-hk/cardano-wallet/wiki/Testing-Yoroi-and-Cardano-wallet#generate-bip-44-addresses) wiki page we already have :+1:

---

# Retrospective

While doing this, we've discovered that functions in `cardano-crypto` weren't sufficient to achieve our goal. Turns out that Yoroi / Icarus' style addresses also using a different seed generation method (more aligned with the BIP-32 specs than the existing implementation).  After fixing this, we were able to produce identical Cardano addresses, regardless if produced from `cardano-cli` in Rust or from `cardano-wallet` in Haskell :tada:

**Comment by piotr-iohk** [comment]
LGTM :+1:
