### ISSUE TITLE
Wrong JSON-Schema / Swagger representation for transaction status.

### ISSUE THREAD

**Issue by KtorZ** [input-output-hk/cardano-wallet-legacy#202]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux) | Code  v Human |

# Context
 
 

Our API documentation is available [here](https://input-output-hk.github.io/cardano-wallet/) and is generated from our Servant API types via their `ToSchema` instances.

We don't currently have any process of reviewing this regularly, and therefore, even if everything is usually in sync, there might be some discrepancy or small quirks in it. For instance, I just found out that our JSON schema representation for `transaction.status` is plain wrong. 

![image](https://user-images.githubusercontent.com/5680256/50757602-2812ec80-1260-11e9-9abd-d252c6bab219.png)

# Steps to Reproduce

1. Open the documentation and have a look at transaction' status ([here](https://cardanodocs.com/technical/wallet/api/v1/#tag/Transactions%2Fpaths%2F~1api~1v1~1transactions%2Fget))

## Expected behavior

Status is represented as a string (an enum with multiple choices).

## Actual behavior
 
<A clear and concise description of what you observe instead. If applicable add screenshots to help explain your problem.>

Status is represented as an object with `tag` and `data` :( (has been like this for the last 10 months...)

---

# Resolution Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #?       | `develop` |

# QA

**Comment by parsonsmatt** [comment]
The Swagger schemas are tested by QuickCheck via the Swagger-ToJSON tests. I believe the instances are fine -- here's the relevant code:

```haskell
transactionStatusToText :: TransactionStatus -> Text
transactionStatusToText x = case x of
    Applying {} ->
        "applying"
    InNewestBlocks {} ->
        "inNewestBlocks"
    Persisted {} ->
        "persisted"
    WontApply {} ->
        "wontApply"
    Creating {} ->
        "creating"

instance ToJSON TransactionStatus where
    toJSON x = object
        [ "tag" .= transactionStatusToText x
        , "data" .= Object mempty
        ]

instance ToSchema TransactionStatus where
    declareNamedSchema _ =
        pure $ NamedSchema (Just "TransactionStatus") $ mempty
            & type_ .~ SwaggerObject
            & required .~ ["tag", "data"]
            & properties .~ (mempty
                & at "tag" ?~ Inline (mempty
                    & type_ .~ SwaggerString
                    & enum_ ?~
                        map (String . transactionStatusToText)
                            allTransactionStatuses
                )
                & at "data" ?~ Inline (mempty
                    & type_ .~ SwaggerObject
                )
            )

instance FromJSON TransactionStatus where
    parseJSON = withObject "TransactionStatus" $ \o -> do
       tag <- o .: "tag"
       case tag of
           "applying" ->
                pure Applying
           "inNewestBlocks" ->
                pure InNewestBlocks
           "persisted" ->
                pure Persisted
           "wontApply" ->
                pure WontApply
           "creating" ->
                pure Creating
           _ ->
                fail $ "Couldn't parse out of " ++ toString (tag :: Text)
```

The serialization instances and the ToSchema instance agree.

**Comment by KtorZ** [comment]
Indeed the swagger schema is correct and matches the json serialization. I didn't dig much when I open the ticket but... the `ToJSON` instance for `TransactionStatus` really feels wrong...

```hs
instance ToJSON TransactionStatus where
    toJSON x = object
        [ "tag" .= transactionStatusToText x
        , "data" .= Object mempty
        ]
```
This is rather inconsistent with the rest of the API. I'd definitely expectTransactionStatus` to serialize toJSON `String`. Anyway. This is indeed a non-bug, our JSON representation is just messed up and there's nothing we can really do without introducing breaking changes...

_sigh_
