### ISSUE TITLE
Swagger JSON-Schema validation test doesn't provide failure-reason

### ISSUE THREAD

**Issue by Anviking** [input-output-hk/cardano-wallet-legacy#205]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux) | Code  |

# Context

We test the validity of our JSON encodings against the swagger schema using a [property test](https://github.com/input-output-hk/cardano-sl/blob/develop/wallet/test/unit/API/SwaggerSpec.hs#L62), ultimately relying on

[`validateJSON :: Definitions Schema -> Schema -> Value -> [ValidationError]`](http://hackage.haskell.org/package/swagger2-2.3.1/docs/Data-Swagger-Internal-Schema-Validation.html#v:validateJSON). Note the returned `[ValidationError]`.
 
 

# Steps to Reproduce

1. Cause failure in https://github.com/input-output-hk/cardano-sl/blob/develop/wallet/test/unit/API/SwaggerSpec.hs#L61 by implementing `ToSchema a` and `ToJSON a` for a type a incorrectly.
2. Look at the test output

## Expected behavior

- Reasons why the test failed are provided in the output

## Actual behavior

- No reasons are provided. Only the object that triggered the failure. This makes failures difficult to debug when working on `ToSchema` instances as a developer.

---

# Resolution Plan

Use `(=== [])` instead of `null` to provide output.

# PR

| Number   | Base      |
| ---      | ---       |
| #203        | `develop` |

# QA 

This is a very small change, that can be verified using the steps above. An explicit example:

1. Cause a failure:
```patch
--- a/src/Cardano/Wallet/API/V1/Types.hs
+++ b/src/Cardano/Wallet/API/V1/Types.hs
@@ -299,7 +299,7 @@ instance ToSchema WalletCoin where
     declareNamedSchema _ =
         pure $ NamedSchema (Just "WalletCoin") $ mempty
             & type_ .~ SwaggerNumber
-            & maximum_ .~ Just (fromIntegral Core.maxCoinVal)
+            & maximum_ .~ Just 2
```

```bash
stack test cardano-wallet:test:unit --ghc-options=-optl-Wl,-dead_strip_dylibs
# Should see something like `["value 5.188812068296707e15 exceeds maximum (should be <=2.0)"] /= []` in output

git revert 02aa37ec90d0dbb4d608d2d400c0f210314236e2 # pr #203 
stack test cardano-wallet:test:unit --ghc-options=-optl-Wl,-dead_strip_dylibs
# No failure reason in output
```

# Retrospective
Maybe there are more problems of the same type in the tests. It would be desirable to make sure the unit tests are likely to provide helpful feedback in all scenarios. The lack of shrinking is also a problem, which would have helped here.

**Comment by piotr-iohk** [comment]
OK! Closing.
