### ISSUE TITLE
Integration tests fail with expectTxStatusEventually: waited too long for statuses.

### ISSUE THREAD

**Issue by piotr-iohk** [input-output-hk/cardano-wallet-legacy#220]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux | Unknown |

# Context
 
Recently I started to observe that my integration scenarios randomly tend to fail on the scenarios which are dealing with wallets that have some coins. The following error is observed:

```
       uncaught exception: IOException of type UserError
       user error (expectTxStatusEventually: waited too long for statuses.)
```

I observe that the issue is more likely to happen when there is more than one wallet *with some coins* used in the scenario, e.g. fails always on such setup code:

```
        forM_ matrix $ \(endpoint, expectations) -> scenario endpoint $ do
            forM_ ([3,6,6,9,0]) $ \coins -> do
                setup $ defaultSetup
                    & initialCoins .~ [coins]
```

The failing expectation `expectTxStatusEventually` that is used in the `setupWallet` waits for the transaction to have `expectTxStatusEventually [InNewestBlocks, Persisted] txn` after the wallet is fed with some coins. The method has a timeout of 60s, but even changing it to 600s does not help for the setup code above.

Also occasionally I saw other tests failing due to this issue (ofc only tests working with wallets with coins), also then changing the timeout did not help. The situation with other tests was strange as at some point they started to work properly again.

It seems that occasionally the tests may fail also on the CI: https://travis-ci.org/input-output-hk/cardano-wallet/jobs/478587172#L894

 

# Steps to Reproduce

1. Following code put in the `scenario` will most likely result in the error:

```
        forM_ matrix $ \(endpoint, expectations) -> scenario endpoint $ do
            forM_ ([3,6,6,9,0]) $ \coins -> do
                setup $ defaultSetup
                    & initialCoins .~ [coins]
```

## Expected behavior

Tests should be passing.

## Actual behavior
 
<A clear and concise description of what you observe instead. If applicable add screenshots to help explain your problem.>

Tests fail with:

```
       uncaught exception: IOException of type UserError
       user error (expectTxStatusEventually: waited too long for statuses.)
```

---

# Resolution Plan

So, it appears that some transactions are flagged as "WontApply" (which is a non-transient status) by the backend and therefore, the DSL keeps on polling transactions hoping for the tx to reach one of the expected status; but it won't, regardless of how long we wait. 

I've added a first "fix" to actually interrupt the polling process if the transaction appears to be in a terminal status that isn't one of the expected one.

Now remains an interesting question: why do some transactions ends not being applying, despite being quite valid. I'll investigate further.

# PR

| Number   | Base      |
| ---      | ---       |
| #318       | `develop` |
| #329       | `develop` |

# QA 

1. Introduced new error banning 0 coin transactions (`ZeroAmountCoin`) and added 1. integration tests for it in `test/integration/Test/Integration/Scenario/Transactions.hs`
2. removed `pendingWith` from the `WALLET_LIST` tests in `test/integration/Test/Integration/Scenario/Wallets.hs`, reorganized tests a bit - now one setup with array of coins initialized is used for an array of GET transactions. Main reason : shorten run time and avoid travis execution limit

**Comment by piotr-iohk** [comment]
@paweljakubas, can you pls fill in QA section on the ticket. Looking at the PRs it should be something like this I think (but please correct and add more if there's more info that could be added):
- Introduced new error banning 0 coin transactions (`ZeroAmountCoin`) and added integration tests for it in `test/integration/Test/Integration/Scenario/Transactions.hs` 
- removed `pendingWith` from the `WALLET_LIST` tests in `test/integration/Test/Integration/Scenario/Wallets.hs`, reorganized tests a bit.

**Comment by paweljakubas** [comment]
@piotr-iohk done

**Comment by piotr-iohk** [comment]
LGTM :+1:
