### ISSUE TITLE
Add disclaimer in API documentation about internal endpoints

### ISSUE THREAD

**Issue by KtorZ** [input-output-hk/cardano-wallet-legacy#228]
# Context

As a follow-up from the discussion in https://github.com/input-output-hk/cardano-wallet/issues/151#issuecomment-454317532, we will add a proper disclaimer in the documentation about the internal endpoints. 

# Decision

These endpoints are part of our API and are documented specifically for Daedalus. However, instead of leaving them stand there without much context, it'll be better to drop a few lines to tell user to NOT use them for anything unless:

- they are ready to deal with possible breaking and behavioral changes
- they truly know what they're doing and know about the consequences

# Acceptance Criterias

1. The API documentation _must_ contain a proper disclaimer for Internal endpoints

---

# Development Plan

- [x] I plan on modifying the `Tags` Servant utility to support adding a description to a swagger tag
- [x] I plan on adding a corresponding description to the internal group

# PR

| Number   | Base      |
| ---      | ---       |
| input-output-hk/cardano-sl#4050       | `develop` |
| #287 | `develop` | 

# QA 

Now visible in the documentation (https://input-output-hk.github.io/cardano-wallet/#tag/Internal):

![](https://user-images.githubusercontent.com/5680256/51991458-6f7d4900-24ab-11e9-8584-cfeecca59cc1.png)

---

# Retrospective

**Comment by KtorZ** [comment]
@piotr-iohk This should also close the topic for #151 (cf your [last comment](https://github.com/input-output-hk/cardano-wallet/issues/151#issuecomment-455086700) on this ticket)

**Comment by piotr-iohk** [comment]
@KtorZ - lgtm. 

However it solves one point from #151. Pls see the last statement in the comment:

>In any case, putting the ticket back to in progress for the remaining items -> https://github.com/input-output-hk/cardano-wallet/issues/151#issuecomment-454721959

If I'm not mistaken these were the remaining actions:

>- manual procedure for proper test for nextUpdate to be done as part of this ticket (here? -> >https://github.com/input-output-hk/cardano-wallet/tree/develop/test/manual)
>
>- create separate ticket for implementing integration test for nextUpdate (based on the manual >procedure)
>
>- restartNode - make attempt to implement such integration test under this ticket (if it turns out >to be more problematic and will require more changes to the cluster, then perhaps create separate >ticket?)
>
>- update API doc (remove /api/internal/postpone-update if that's the case, say /api/internal/apply->update is only restarting the node - if that's the case)
