### ISSUE TITLE
Finalize HD hierarchy for EOS-wallets

### ISSUE THREAD

**Issue by denisshevchenko** [input-output-hk/cardano-wallet-legacy#231]
# Context

We want to unify `Hd` type hierarchy for EOS-wallets. The main goal is to use existing `Hd***`-types as much as possible. Furthermore, we want to unify `HdRootId` both for FO-wallets and EOS-wallets, with backward-compatibility.

# Decision

# Acceptance Criterias

---

# Development Plan

- [x] Update `HdRootId` type to something more opaque.
- [x] Introduce a new branch in `HdAccount` to have room for EO stuff (without implementing anything on E.O side yet, but just making sure that the existing F.O. stuff keeps on working fine).
- [x] Add EO-specific stuff in EO-branch in `HdAccountBase`.
- [x] Replace `EosHd***` types by their equivalent `Hd***` types and leverage the `HdAccount` branch to store and retrieve the relevant information.
- [x] Change API-request for EOS-wallet creation: user must provide not only list of accounts' public keys, but list of their indexes as well.
- [x] `getAddressPool` function is added.

Separate PRs will be opened for each of steps.

# PR

| Number   | Base      |
| ---      | ---       |
| #225       | `develop` |
| #243       | `develop` |
| #247       | `develop` |
| #250       | `develop` |
| #255       | `develop` |
| #256       | `develop` |
| #273        | `develop` |

# QA 

| Criteria | Coverage |
| ---      | ---      |
| ?        | -        |

Technically, this issue is (mostly) about code refactoring/restructuring, not about new features. The only exception is:

> Change API-request for EOS-wallet creation: user must provide not only list of accounts' public keys, but list of their indexes as well.

But this change is _already_ covered by tests in PR #334.

---

# Retrospective

**Comment by KtorZ** [comment]
@denisshevchenko What's missing to send this one in QA :thinking: ?

**Comment by piotr-iohk** [comment]
Well, there is QA section missing ^^ ;)
@denisshevchenko, can you fill it in please?

**Comment by piotr-iohk** [comment]
lgtm :+1:
