### ISSUE TITLE
Remove WIP Paths and expose them in the API

### ISSUE THREAD

**Issue by KtorZ** [input-output-hk/cardano-wallet-legacy#235]
# Context

We marked #100 as done though, related endpoints for externally owned wallets are still under a WIP path and not quite ready to be used by anyone. 
In order to really be able to wrap this up, we do need to expose those endpoints through the API first.

# Decision

We'll expose those WIP paths through "normal" API sections and make them part of the existing public API.

# Acceptance Criterias

1. The API _must_ expose endpoints to deal with externally owned wallets (CRUD operations)
1. WIP modules _must_ disappear 

---

# Development Plan

- [x] I intend to remove WIP modules
- [x] I intend to expose new endpoints for to E.O. wallets in the API behind a proper prefix

# PR

| Number   | Base      |
| ---      | ---       |
| #235 | `develop` |

# QA 

| Criteria | Coverage |
| ---      | ---      |
| 1.  & 2.      | Endpoints have been removed, or more or less, moved into relevant places in the API: [here](https://github.com/input-output-hk/cardano-wallet/blob/a0da59848750e28762c2ac713242eba47613a61b/src/Cardano/Wallet/API/V1/Transactions.hs#L35-L43) and [here](https://github.com/input-output-hk/cardano-wallet/blob/a0da59848750e28762c2ac713242eba47613a61b/src/Cardano/Wallet/API/V1/Wallets.hs#L45-L85). The result can be viewed in the API documentation [here](https://input-output-hk.github.io/cardano-wallet/#tag/Externally-Owned-Wallets) and [here](https://input-output-hk.github.io/cardano-wallet/#tag/Transactions%2Fpaths%2F~1api~1v1~1transactions~1unsigned%2Fpost) and [here](https://input-output-hk.github.io/cardano-wallet/#tag/Transactions%2Fpaths%2F~1api~1v1~1transactions~1externally-signed%2Fpost)

---

# Retrospective

This turned out to be a pain in the *** for a completely unrelated thing. Integration tests failed (for a good reason) because it wasn't possible to retrieve the API documentation from the server anymore. The reason why the documentation couldn't be generated was silently swallowed by some exception handler in our code. Debugging this was painful and long but I finally found the guilty `Example PublicKey` instance throwing hard because of an unsafe `(!!)` usage. I've open a follow-up ticket (#244) to make sure we crash the node or, correctly report an error when this kind of failure happens. We are doing quite a few _unsafe_ things in the swagger generation process, and this kind of pointless debugging could be avoided with a proper error reporting in a first place.

**Comment by piotr-iohk** [comment]
>The result can be viewed in the API documentation [here][TODO-LINK-TO-API-DOC]

Can you please provide link to API documentation exposing this? I cannot find it here -> https://input-output-hk.github.io/cardano-wallet/ (perhaps not looking in the right place?)

**Comment by KtorZ** [comment]
You're looking in the right place. Aaaaand... it's not there. The documentation isn't actually uploaded anymore: 

https://travis-ci.org/input-output-hk/cardano-wallet/jobs/483553527

We forgot to update the CI configuration when we changed the executable name. I'll open a corresponding bug and fix ASAP.

**Comment by KtorZ** [comment]
@piotr-iohk Documentation was uploaded successfully :+1:, link above have been updated.

**Comment by piotr-iohk** [comment]
LGTM :)
