### ISSUE TITLE
Write integration tests for (and finalize implementation of) creation of E.O.S wallets

### ISSUE THREAD

**Issue by KtorZ** [input-output-hk/cardano-wallet-legacy#236]
# Context

Ideally, we want to replay most of our existing integration test suite for F.O. wallets against E.O. wallets (where it makes sense). As a first step, we want to at least cover the creation of such wallets and make sure we can correctly send API requests.

# Decision

Cover creation of E.O.S wallets via integration tests.

# Acceptance Criterias

- [x] Creation of E.O.S Wallets _should_ be tested and covered in CI.

---

# Development Plan

- [x] Review creation of EOS wallet (API Types, Wallet Layer, Kernel and Acid State layers)
- [x] Implement dummy getter / read endpoint for EOS wallet
- [x] Write a scenario testing creation + lookup of E.O. wallet
- [x] Add an extra guard to EOS wallet creation to make sure that given wallets can actually only be created from a _consistent_ non empty list of accounts
- [x] More testing scenarios to illustrate the above.

# PR

| Number   | Base      |
| ---      | ---       |
| #277 | `develop` |
| #305 | `develop` |
| #307 | `develop` |
| #311 | `develop` |
| #310 | `develop` | 
| #325 | `develop` |

# QA 

| Criteria | Coverage |
| ---      | ---      |
| 1.      | This is rather "basic" (cf [Scenario/EosWallets](https://github.com/input-output-hk/cardano-wallet/blob/develop/test/integration/Test/Integration/Scenario/EosWallets.hs)) but really aims at testing the core capabilities of the E.O.S wallet (DB layer and such), making sure we aren't doing anything crazy there. Eventually, we want to add more test here about other parameters of the payload (e.g. assuranceLevel or name) in a very similar fashion as we did for fully owned wallet. Yet, I'd rather leave that for a bit later for now and move on with the testing the rest of the core capabilities.  |

**Comment by piotr-iohk** [comment]
lgtm :+1: 
(with the assumption this suite will be extended in the nearest future)
