### ISSUE TITLE
Prepare cardano-sl/wallet for the release 1.5

### ISSUE THREAD

**Issue by KtorZ** [input-output-hk/cardano-wallet-legacy#251]
# Context

We've frozen development on `cardano-sl/wallet` some times ago. However, the branch has been left partly "abandoned" and we've only taken care of applying bug fixes to this. Still, integration tests aren't available on `cardano-sl/wallet` and we haven't quite controlled whether it indeed includes all the patches from 1.4.x. 
Also, there are maybe a few things to review from the API documentation and the build instructions. 

# Decision

All-in-all, we need to spend time on this figuring out what's in for the release, what's missing, and document it.

# Acceptance Criterias

1. [x] Integration tests _must_ be enabled on `cardano-sl/wallet`, at least locally
2. [x] All (relevant) patches from 1.3.x & 1.4.x _must_ be listed 
3. [x] All (relevant) patches from 1.3.x & 1.4.x _must_ have been applied to `cardano-sl/wallet` 
4. [x] A clear inventory of the features, fixes & improvements currently present in `cardano-sl/wallet` _must_ be established and documented as part of the CHANGELOG
5. [x] Undesired features present in `cardano-sl/wallet` (and added since 1.4) _may_ be removed.

---

# Development Plan

- I intend to finalize cleanup of `cardano-sl` for anything externally-owned wallets or BIP-44 related
- I intend to revert some commits about decoupling that happened in the wallet (the bits removing the NodeStateAdaptor in favor of the NodeClient)
- I intend to backport the wallet integration tests on `cardano-sl` (solving "merge" conflicts on sl)
- I intend to make a full list of changes and PR we merged on `sl` since 1.4.0 and that will be included in 1.5.0

# PR

| Number   | Base      |
| ---      | ---       |
| input-output-hk/cardano-sl#4045       | `develop` |
| input-output-hk/cardano-sl#4046       | `develop` |
| input-output-hk/cardano-sl#4047       | `develop` |
| input-output-hk/cardano-sl#4054        | `develop` |
| input-output-hk/cardano-sl#4051        | `develop` |

# QA 

| Criteria | Coverage |
| ---      | ---      |
| 1.        | Integration tests have been backported and merged into develop (cf input-output-hk/cardano-sl#4047) and they even run in the hydra CI https://hydra.iohk.io/build/588876/log :tada:      |
| 2. 3. 4. | CHANGELOG added to reflect the actual history on `cardano-sl/develop` input-output-hk/cardano-sl#4054 |
| 5. | Remaining PRs have cleaned-up a few things that had either incorrectly made to `develop` or, needed some tweaking (like, making the new node monitoring API optional and disable by default, to preserve the existing behavior). | 

---

# Retrospective

**Comment by piotr-iohk** [comment]
LGTM :+1:
