### ISSUE TITLE
Documentation isn't build nor uploaded from the CI anymore 

### ISSUE THREAD

**Issue by KtorZ** [input-output-hk/cardano-wallet-legacy#252]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux) | Configuration |

# Context
 
 

The CI has a special "documentation" job when things get merged into develop. This builds the documentation and publish it to the right `gh-pages` branch (then hosted here: https://input-output-hk.github.io/cardano-wallet/). However, this job is "allowed to fail" since the script will abort when there's actually nothing to push. 

The failure happened after we renamed the executables, but forgot to do it in the travis configuration.

# Steps to Reproduce

1. Merge something into develop
1. Wait for the "Documentation" job to fail

## Expected behavior

When there's an API change, the documentation is built and published to the repository's gh-pages

## Actual behavior
 
<A clear and concise description of what you observe instead. If applicable add screenshots to help explain your problem.>

https://travis-ci.org/input-output-hk/cardano-wallet/jobs/483553527

---

# Resolution Plan

- [x] Provide the right executable in the travis configuration
- [x] (bonus) Ideally, make this job "required" and find a work-around when there's nothing to push

# PR

| Number   | Base      |
| ---      | ---       |
| #253        | `develop` |

# QA 

The documentation job is back https://travis-ci.org/input-output-hk/cardano-wallet/jobs/483806387 and works correctly. It should now run fine even if there's nothing to upload.

**Comment by piotr-iohk** [comment]
LGTM
