### ISSUE TITLE
Check uniqueness during EOS-wallet creation

### ISSUE THREAD

**Issue by denisshevchenko** [input-output-hk/cardano-wallet-legacy#270]
# Context

When we create new EOS-wallet, we receive a list of accounts' public keys and indexes. But this list _can_ contain the same public key and/or same index twice. Moreover, it is possible to receive the same account's public key for _different_ EOS-wallets (which doesn't make sense, because all accounts in all EOS-wallets must be unique).

# Decision

We must check uniqueness of accounts' public keys and indexes during EOS-wallet creation.

UPDATE from @KtorZ:

> Ideally, I'd rather make it impossible to represent a list of account public keys with duplicate for externally owned wallets. Maybe it's too much efforts here but you know, using a `Set` for instance, or having smart constructors used in the JSON unserializer.

# Acceptance Criterias

1. When we create new EOS-wallet, all accounts' public keys and indexes (in received list) _must_ be unique across ALL knowns account public keys.
2. When we create new EOS-wallet, all accounts' public keys _must_ differ from ones in all _existing_ EOS-wallets.

---

# Development Plan

- [ ] All public keys and indexes should be checked in `WalletLayer`: if they are not unique - return an error.
- [ ] Before `HdRoot` creation all received public keys must be checked: if `acid-state` _already_ contains `HdAccount` with such a key - return an error.

# PR

| Number   | Base      |
| ---      | ---       |
| #?       | `develop` |

# QA 

| Criteria | Coverage |
| ---      | ---      |
| ?        | -        |

---

# Retrospective

**Comment by KtorZ** [comment]
Superseded by #236 and #325 :+1:
