### ISSUE TITLE
Investigate CI failure:  Node getNodeInfo ForceNtpCheck

### ISSUE THREAD

**Issue by KtorZ** [input-output-hk/cardano-wallet-legacy#279]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux) | Code  v Configuration  |

# Context
 
 

We made a first attempt to fix the node HTTP client timeout in #261, yet the failure has occurred again in the following job:

https://travis-ci.org/input-output-hk/cardano-wallet/jobs/486294382

Looking at the raw logs, we can find this:

```
GET Request #660
    :> api
    :> v1
    :> node-info
    :> 'force_ntp_check' field: force ntp check

[...]

Response #660 30.007827893s
```

So, the response took _slightly_ more than 30s, and the test still fails. So maybe we haven't modified the right timeout :thinking: ?

# Steps to Reproduce

1. Run the integration tests, multiple times
2. Watch for "Node getNodeInfo ForceNtpCheck"

## Expected behavior

This test passes with success all the time. 

## Actual behavior
 
<A clear and concise description of what you observe instead. If applicable add screenshots to help explain your problem.>

Sometimes, the CI fails with:

```
  test/integration/Test/Integration/Framework/DSL.hs:167:23: 
  1) Node getNodeInfo ForceNtpCheck
       uncaught exception: IOException of type UserError
       user error (expected a successful response but got an error: ClientHttpError (ConnectionError "HttpExceptionRequest Request {\n  host                 = \"127.0.0.1\"\n  port                 = 8090\n  secure               = True\n  requestHeaders       = [(\"Accept\",\"application/json;charset=utf-8,application/json\")]\n  path                 = \"/api/v1/node-info\"\n  queryString          = \"?force_ntp_check\"\n  method               = \"GET\"\n  proxy                = Nothing\n  rawBody              = False\n  redirectCount        = 10\n  responseTimeout      = ResponseTimeoutDefault\n  requestVersion       = HTTP/1.1\n}\n ResponseTimeout"))
```

---

# Resolution Plan

Ensure that `managerResponseTimeout` is set everywhere.

I believe, the request is sent from the integration tests to the node in the following manner:
```
Node <-> Node server <-> Node client <-> Wallet Server <-> Wallet client <-> integration tests
```

Initially (#261) we increased the timeout in the *node* client, but not the *wallet* client. By modifying `mkHttpsManagerSettings` upstream we changed both at once.

# PR

| Number   | Base      |
| ---      | ---       |
| #261       | `develop` |
| input-output-hk/cardano-sl#4055       | `develop` |
| #297        | `develop` |

# QA 

I have run the failing test multiple times after the fix, using the following patch and command:
```
stack test cardano-wallet:integration --ta '--match "/Node/getNodeInfo ForceNtpCheck/"' --ghc-options=-optl-Wl,-dead_strip_dylibs
```

```patch
diff --git a/test/integration/Test/Integration/Scenario/Node.hs b/test/integration/Test/Integration/Scenario/Node.hs
index 137a0022e..6db1a7878 100644
--- a/test/integration/Test/Integration/Scenario/Node.hs
+++ b/test/integration/Test/Integration/Scenario/Node.hs
@@ -17,7 +17,7 @@ spec = do
     scenario "getNodeSettings" $ do
         void $ successfulRequest Client.getNodeSettings
     scenario "getNodeInfo ForceNtpCheck" $ do
-        void $ successfulRequest $ Client.getNodeInfo $- ForceNtpCheck
+        replicateM_ 10 $ successfulRequest $ Client.getNodeInfo $- ForceNtpCheck
     scenario "getNodeInfo NoNtpCheck" $ do
         void $ successfulRequest $ Client.getNodeInfo $- NoNtpCheck
     scenario "nextUpdate" $ do
```

I am not sure if we want the `replicateM_ 10` thing on CI / `develop`. Increasing it to the point where the test takes 30 s seems to be the only way to surely reproduce the bug.

**Comment by Anviking** [comment]
Hm. On initial investigation I've found (will check more later)
- inserting `threadDelay` of 31 s to the node server handler, curling the node -> WORKS
- inserting `threadDelay` of 30 s to the wallet server handler, curling the wallet -> WORKS (need to double check)
- inserting `threadDelay` of 30 s to the wallet server internal node client handler, curling the wallet -> WORKS (need to double check)

🤔 🤔 🤔

**Comment by piotr-iohk** [comment]
fyi, just had that failure on my pr -> https://travis-ci.org/input-output-hk/cardano-wallet/jobs/486450230

**Comment by parsonsmatt** [comment]
It's possibly the HTTP client request that's causing it -- [the settings for an `HttpManager`](http://hackage.haskell.org/package/http-client-0.6.1/docs/Network-HTTP-Client.html#v:managerResponseTimeout) have a `managerResponseTimeout` field which defaults to 30 seconds.

**Comment by Anviking** [comment]
> the HTTP client

So we tried that… for the node client in #261

On the other hand, is there not some kind of HTTP client inside the test infrastructure itself?

Maybe that was what you meant xD 

*investigating*

*modified the wallet client manager, recompiling and running tests*

**Comment by KtorZ** [comment]
@Anviking Good point. Though it's not the one firing the requests here I think.

**Comment by Anviking** [comment]
I think it is. And I think it just passed 100 retries of `getNodeInfo ForceNtpCheck` :D

**Comment by piotr-iohk** [comment]
lgtm :+1:
