### ISSUE TITLE
Add boundary integration tests for multioutput transactions

### ISSUE THREAD

**Issue by paweljakubas** [input-output-hk/cardano-wallet-legacy#290]
# Context

The coin selection works by trying to maintain a one-to-one ratio between the outputs and change _of a same wallet_. So, for each output, there's a corresponding change output. Meaning that, after a multi-output transactions, the number of available UTxO tends to be constant. However, this can be not always true. If more than one inputs have to be selected to cover a single output (regardless of whether we include fees or not), or because, the change output may overflow so we need to have two change output for a single output .

We want to have those boundary cases tested.

# Decision
Add respective tests for multioutput transactions in integration suite.

# Acceptance Criterias

1. The added tests cover boundary conditions when the number of utxo may not be the same after the multioutput transaction

---

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #?       | `develop` |

# QA 

| Criteria | Coverage |
| ---      | ---      |
| ?        | -        |

---

# Retrospective

**Comment by KtorZ** [comment]
This is a duplicate / part of #190 
@paweljakubas, In such case, you may just add a point to your development plan :+1:

**Comment by paweljakubas** [comment]
ok, did it
