### ISSUE TITLE
Address Pool Module

### ISSUE THREAD

**Issue by KtorZ** [input-output-hk/cardano-wallet-legacy#33]
# Context

<What is the issue that we are seeing that is motivating this decision or
change. Give any elements that help understanding where this issue comes from.
Leave no room for suggestions or implicit deduction.>

Here, we are looking for a module which can keep track of address pools and answer the question:

```hs
isOurs: Address -> Maybe (WalletId, AccountId) 
```

This can be achieve in various way but a few pointers:

- We can have an opaque `AddressPool` types which is implemented behind the scene as some specific 
  data-structure (like a `Map`); managing this structure is what the module does.

- How to generate new items should be provided to the module (ideally, the module doesn't know about addresses).

- We should have a way to initialize the module from a list of items to track.

# Decision

<Give details about the architectural decision and what it is doing. Be
extensive: use schemas and references when possible. Do not hesitate to use
schemas and references when possible.>

FIXME: To be completed with design decision (@uroboros)

# Acceptance Criteria

<Use standard vocabulary to describe requirement levels RFC-2119: Must-Should-May.
e.g.: The API _must_ support creation of wallets through a dedicated endpoint.>

1. - [x] `cardano-wallet` _should_ provide a new module to host Address Discovery utilities as explained in BIP-44.
1. - [x] The module from #33.1 _should_ provide an abstract and self-contained API.

---

# PR

| Number    | Base      |
| ---       | ---       |
| [118][PR-1] | `develop` |
| [129][PR-2] | `develop` |

[PR-1]: https://github.com/input-output-hk/cardano-wallet/pull/118
[PR-2]: https://github.com/input-output-hk/cardano-wallet/pull/129

# QA 

<WHEN IN PROGRESS> 
<How are we covering acceptance criteria. Give here manual steps or tests that
are covering the above criteria.>

| Criteria | Coverage |
| --- | --- | 
| Creation & validation of address gap | See [Spec/AddressPoolGap](https://github.com/input-output-hk/cardano-wallet/blob/develop/test/unit/Test/Spec/AddressPoolGap.hs) |
| Creation, lookups and extension of address pool | See [Spec/AddressPool](https://github.com/input-output-hk/cardano-wallet/blob/develop/test/unit/Test/Spec/AddressPool.hs) |

```
$ stack test cardano-wallet:unit --test-arguments "--match Pool"
AddressPool
  lookupAddressPool
    +++ OK, passed 100 tests:
    62% hit outside pool
    38% hit within pool
AddressPoolGap
  mkAddressPoolGap
    +++ OK, passed 100 tests:
    69% gap outsides boundaries
    31% gap within boundaries
```

# Retrospective

**Comment by uroboros** [comment]
Core algorithm -> https://github.com/input-output-hk/cardano-wallet/pull/73
