### ISSUE TITLE
Review Prefiltering 

### ISSUE THREAD

**Issue by KtorZ** [input-output-hk/cardano-wallet-legacy#34]
# Context

With #33, we should have the necessary tools to perform account discovery while
applying blocks. Answering the question `isOurs` happens during pre-filtering
where we skim through incoming blocks, looking for inputs that are related to
our wallet(s).

# Decision

Using the address pool module, we should be able to abstract away the account
discovery to use the relevant method depending on whether we have a F.O. wallet
or an E.O. one.

# Acceptance Criterias

1. Addresses derived sequentially _can_ be identified during pre-filtering
1. Addresses derived randomly _must_ still be identifiable during pre-filtering
1. Pre-filtering _may_ make use of the module from #33.1

---

# Development Plan

- [x] Abstract over wallet/account/address ids
- [x] Parametrise prefiltering code with IsOurs + PrefilterKey, separate HdRnd from generic prefiltering module
- [x] Review pre-filtering implementation all-in-all
    - [x] Review definition of "PrefilteredBlock" and remove addresses from it
    - [x] Unify "AddrWithId" and "HdAddress" types
    - [x] Rewrite pre-filtering for single accounts, without considering metadata (yet).
    - [x] Introduce multi-accounts pre-filtering to avoid traversing a block n times (n = number of accounts)
    - [x] Compute metadata on the prefiltered result (instead of during prefiltering)
    - [x] Update usage of prefiltering functions in BListener and Restoration
- [ ] ~~Instantiate prefiltering with sequential derivation~~
- [x] Review corresponding unit tests to work with either sequential or random derivation (and test both)

# PR

| Number | Base      |
| ---    | ---       |
| #139   | `develop` |
| #179 | `develop` |
| #180 | `develop` |
| #181 | `develop` |
| #183 | `develop` |
| #192 | `develop` |
| #204 | `develop` |

# QA

### IsOurs

This was a big one but has finally landed. The _major_ and most important change is actually fairly simple but allows to abstract over the pre-filtering (resp. recovery) process by having the implementation working with a generic "IsOurs" interface.

https://github.com/input-output-hk/cardano-wallet/blob/e1526cbc931af11d4d1ff05c8563813a4772dd22/src/Cardano/Wallet/Kernel/DB/HdWallet.hs#L214-L225

which goes together with:

https://github.com/input-output-hk/cardano-wallet/blob/e1526cbc931af11d4d1ff05c8563813a4772dd22/src/Cardano/Wallet/Kernel/Prefiltering.hs#L93-L99

So, by having `prefilterBlock` works with any _isOurs_ function that satisfies the interface, we makes it possible to support multiple scheme here and are free to answer the question the way we'd like (i.e. using a root private key like for F.O. wallets or a pool of account public key like for E.O. wallets).

### Statefulness 

An important thing to notice from the `isOurs` interface above is that it's seemingly stateful:

```hs
isOurs :: Address -> s -> (Maybe HdAddress, s)
```
So, given a state `s`, we return a corresponding address and the new state. This plays nicely with our existing address pool module:

https://github.com/input-output-hk/cardano-wallet/blob/e1526cbc931af11d4d1ff05c8563813a4772dd22/src/Cardano/Wallet/Kernel/AddressPool.hs#L94-L99

`s` is here the `AddressPool address` :) . Then, it's a matter of persisting and merging the state between queries. The statefulness is rather useless for F.O. wallets since the underlying state doesn't change (and is actually discarded by the `BListener` and the `Restore` modules). Yet, it's essential for E.O. wallets as they discover new addresses.

### E.O. Instance

Note that, we do not _yet_ provide an instance of `IsOurs` because we need to resolve #32 first and have our data-model sorted out for E.O. wallets. Yet, it'll be fairly easy to write once we have that. I'll create a corresponding ticket for both this and the restoration procedure to tight all this together once #32 and a couple of others have landed.

### Testing

In terms of testing, since this was mostly a refactor of our exacting source code, we've made sure that existing tests worked in a similar fashion as before. Locally, I've also added some noise during integration tests to make sure prefiltering happened correctly (as suggested in #184 and explained in https://github.com/input-output-hk/cardano-wallet/pull/204#issuecomment-454423456) 

In a second stage, we will want to sync with mainnet, restore an existing wallet and see what's going on here. I'd rather keep that for #40 or, once we have fully integrated E.O. to make it easier to setup.

---

# Retrospective

This issue was much bigger than initially estimated. Our main mistake here was not to anticipate the amount of work needed in the prefiltering code to make it ready for BIP-44. So, instead of just implementing a new feature, we had to re-implement the base feature first. 
This is symptomatic in more part of the code base actually, and there are still few modules that _need some love_. Therefore, this kind of redesigns / heavy refactorings should become an ongoing process to prevent code from rotting in the long run.

**Comment by uroboros** [comment]
first PR on this -> https://github.com/input-output-hk/cardano-wallet/pull/139

**Comment by piotr-iohk** [comment]
>  Locally, I've also added some noise during integration tests to make sure prefiltering happened correctly

Nice! Hope it gets into `develop` soon :)
