### ISSUE TITLE
Finalize CRUD operations for E.O.S Wallets

### ISSUE THREAD

**Issue by KtorZ** [input-output-hk/cardano-wallet-legacy#36]
# Context

<What is the issue that we are seeing that is motivating this decision or
change. Give any elements that help understanding where this issue comes from.
Leave no room for suggestions or implicit deduction.>

Until here, we didn't need the remaining classic CRUD operations on E.O.S. wallets.

# Decision

<Give details about the architectural decision and what it is doing. Be
extensive: use schemas and references when possible. Do not hesitate to use
schemas and references when possible.>

 For completeness and because we want to make our users happy, let's implement (and test) them.

# Acceptance Criteria

<Use standard vocabulary to describe requirement levels RFC-2119: Must-Should-May.
e.g.: The API _must_ support creation of wallets through a dedicated endpoint.>

1. - [x] The API _must_ support 'Read' operation on E.O.S. Wallets.
2. - [x] The API _must_ support 'Update' operation on E.O.S. Wallets.
3. - [x] The API _must_ support 'Delete' operation on E.O.S. Wallets.
4. - [x] The API _must_ support 'List' operation on E.O.S. Wallets.
5. - [x] The 'Update' operation from #36.2 _may_ act upon the followings: name, assurance level, address gap.

---

# PR

| Number   | Base      |
| ---      | ---       |
| #278       | `develop` |
| #304       | `develop` |

# Consequences

<To be completed in retrospective. What becomes easier or more difficult to do
because of this change.>

**Comment by piotr-iohk** [comment]
@denisshevchenko, @KtorZ  
There is no QA section on the ticket, however I understand that it is an old format. :)
In any case, in terms of QA, I think we should add some integration tests for CRUD operations. Probably we want to approach this in different task? (I haven't found any, so if there is one can you point me to it pls?).

There are some tests already added in #236. But they only touch on create and read. There are no tests covering list, update, delete.

**Comment by KtorZ** [comment]
Indeed there's no QA / tests for this _yet_. I'll leave that decision to @denisshevchenko here; would you rather write them as part of this ticket? Or should we open another ticket a bit like #236 where you or I can write those integration tests?

**Comment by piotr-iohk** [comment]
@denisshevchenko I'm closing this one. As discussed I'll be adding more integration tests for EOS wallets CRUD operations under #331.
