### ISSUE TITLE
Make unit tests run faster

### ISSUE THREAD

**Issue by Anviking** [input-output-hk/cardano-wallet-legacy#38]
# Description
WIP Description

# Acceptance Criteria

- [x] `wallet-unit-tests` should take less than 15 minutes on CI (Travis presumably)

Takes 13 minutes [here](https://travis-ci.org/input-output-hk/cardano-wallet/jobs/453964484) including building the tests.

# PR

| Number    | Base      |
| ---       | ---       |
| [#49][PR-1] | `develop` |

[PR-1]: https://github.com/input-output-hk/cardano-wallet/pull/39

**Comment by Anviking** [comment]
Moving out spending passwords generation seemed like it could help *a little*.
https://github.com/input-output-hk/cardano-sl/blob/develop/wallet-new/test/unit/Test/Spec/Fixture.hs#L41
2.2 s with 0% spending passwords
3.2 with 80% spending password, 20% without
3.0 - 3.6 with 100% spending passwords

And also managed to re-use the same spending password for all.

**Comment by Anviking** [comment]
Next step: only generate a few wallets & addresses and reuse them for all tests.

**Comment by KtorZ** [comment]
@Anviking 

Think about making multiple PRs introducing your changes incrementally. No need to go for the final solution right away :)

**Comment by Anviking** [comment]
[anviking/38/faster-tests-2](https://github.com/input-output-hk/cardano-sl/compare/anviking/38/faster-tests-2?expand=1) 🤔 I think this calls out: is there really anything we want to QuickCheck?

On develop the only things we're  generating randomly are:
- [`Maybe V1.SpendingPassword`](https://github.com/input-output-hk/cardano-sl/blob/develop/wallet-new/test/unit/Test/Spec/Addresses.hs#L102) (expensive to compute)
-  [`? V1.NewWallet`](https://github.com/input-output-hk/cardano-sl/blob/develop/wallet-new/test/unit/Test/Spec/Addresses.hs#L103) (expensive to compute)
-  [`ProtocolMagic`](https://github.com/input-output-hk/cardano-sl/blob/develop/wallet-new/test/unit/Test/Spec/Addresses.hs#L426)

Simplest solution would be setting `withMaxSuccess` to like `2`… Or in some sense abandoning QuickCheck `PropertyM`.

**Comment by Anviking** [comment]
Next step: `withMaxSuccess 5` everywhere, and if it works, create a new separate issue for improving tests and removing QuickCheck where it's not needed.

**Comment by Anviking** [comment]
~To note: removing `parallel` didn't seem to do anything in particular. 
[`parallel` removed](https://travis-ci.org/KtorZ/cardano-wallet/builds/452847395)
[`parallel` still there](https://travis-ci.org/KtorZ/cardano-wallet/builds/452832247)~

**Comment by KtorZ** [comment]
Duplicated by #1
