### ISSUE TITLE
BIP-44 Utils Part II: Hardened Derivations

### ISSUE THREAD

**Issue by KtorZ** [input-output-hk/cardano-wallet-legacy#41]
# Context

<What is the issue that we are seeing that is motivating this decision or
change. Give any elements that help understanding where this issue comes from.
Leave no room for suggestions or implicit deduction.>

This is finalizing the work started in #31 but including private key derivations and operations this time.

# Decision

<Give details about the architectural decision and what it is doing. Be
extensive: use schemas and references when possible. Do not hesitate to use
schemas and references when possible.>

Extend the module defined in #31 to also support hardened derivation.

# Acceptance Criteria

<Use standard vocabulary to describe requirement levels RFC-2119: Must-Should-May.
e.g.: The API _must_ support creation of wallets through a dedicated endpoint.>

1. The module from #31.1 _must_ provide utils to perform child derivation of account private keys from root private keys.
2. The module from #31.1 _must_ provide utils to perform child derivation of address private keys from account private keys.
3. The module from #31.1 _must_ provide utils to perform public key derivation from private keys.

# Development Plan

 - [x] I plan on adding method to derive account private key from root/master private key
      - deriving through `purpose'` and `coin_type'` internal derivations
 - [x] I plan on adding method to derive address private key from account private key
      - deriving through `change` internal derivation
 - [x] I plan on adding method to derive extended public key from extended private key
 - [x] I plan on fixing current method for deriving address public key from account public key
      - https://github.com/input-output-hk/cardano-wallet/pull/133/files#diff-ab6bdce941f09e40581d4a2debad9d7aR26
      - should go through `change` internal derivation
 - [x] Open an issue for adding golden tests for every method above
      - Nicolas advised to use rust's `cardano-cli` to generate golden tests https://github.com/input-output-hk/cardano-cli, https://cardanorust.iohkdev.io/cli-wallet/
      - use `cardano-cli` instructions https://github.com/input-output-hk/cardano-wallet/wiki/Testing-Yoroi-and-Cardano-wallet
      - https://github.com/input-output-hk/cardano-wallet/issues/195
 - [x] respect naming convention "normal" vs "non-hardened"
      - poll https://input-output-rnd.slack.com/archives/GBT05825V/p1546277012162200
 - [x] I plan on adding additional unit/property tests
      - steal them from `cardano-crypto` lib, have a look at `cardano-cli`
 - [x] Open an issue for adding an isomorphic type to `Word31`
      - https://github.com/input-output-hk/cardano-wallet/pull/170#discussion_r243156715
      - https://github.com/input-output-hk/cardano-wallet/pull/170#discussion_r243161983
      - https://github.com/input-output-hk/cardano-wallet/issues/189
- [x] Add an arbitrary generator for hardened and non-hardened indexes and keys
      - either as a seperate wrapper type or wrapper around isomorphic `Word31`
- [x] Open an issue to check coverage with quickcheck's `cover`
      - https://github.com/input-output-hk/cardano-wallet/issues/188
- [x] Open an issue for adding bip32 property tests to `cardano-crypto`
      - https://github.com/input-output-hk/cardano-wallet/pull/169#discussion_r244298140
      - https://github.com/input-output-hk/cardano-wallet/issues/187
- [x] Open an issue to fix `quickcheck`s `arbitrarySizedBoundedIntegral`
      - https://github.com/input-output-hk/cardano-wallet/pull/169/commits/ce4cedfe9fe0a878416dd89ea71a1f5ad25c75d9#diff-e9a62968e1cca775db414be6d317ecadR43
      - https://github.com/input-output-hk/cardano-wallet/issues/186

---
# PR

| Number | Base      |
| ---    | ---       |
| https://github.com/input-output-hk/cardano-wallet/pull/162  | `develop` |
| https://github.com/input-output-hk/cardano-wallet/pull/163  | `develop` |
| https://github.com/input-output-hk/cardano-wallet/pull/169  | `develop` |
| https://github.com/input-output-hk/cardano-wallet/pull/170  | `develop` |

# QA

| Criteria | Coverage |
| ---      | ---      |
| 1.       | Has been covred with property tests (see bellow) |
| 2.       | Has been covred with property tests (see bellow) |
| 3.       | Has been covred with property tests. It is not explicitely tested but implicitely through property `equals to deriving address private key and extracting public part from it: N(CKDpriv((kpar, cpar), i)) === CKDpub(N(kpar, cpar), i)`|
| -       | Additionally this PR fixes address public key derivation from account public key (previous version wasn't bip44 compatible - it was missing internal change chain derivation). This PR adds missing change chain derivation and adds property tests (see bellow) |

```
$ stack test --ta '-m "Ed25519Bip44"' cardano-wallet:unit
Ed25519Bip44
  Deriving address public key
    fails if address index is hardened
      +++ OK, passed 100 tests.
    succeeds if address index is non-hardened
      +++ OK, passed 100 tests.
    equals to deriving address private key and extracting public part from it: N(CKDpriv((kpar, cpar), i)) === CKDpub(N(kpar, cpar), i)
      +++ OK, passed 100 tests.
  Deriving address private key
    fails if address index is hardened
      +++ OK, passed 100 tests.
    succeeds if address index is non-hardened
      +++ OK, passed 100 tests.
    fails if passwords differ
      +++ OK, passed 100 tests.
    succeeds if passwords are equal
      +++ OK, passed 100 tests.
  Deriving account private key
    fails if account index is non-hardened
      +++ OK, passed 100 tests.
    succeeds if account index is hardened
      +++ OK, passed 100 tests.

Finished in 186.8338 seconds
9 examples, 0 failures
```

---

# Retrospective

There was a `cardano-crypto` bug discovered (https://github.com/input-output-hk/cardano-crypto/pull/52) during this issue which is great - but it took some time to debug and fix it upstream. Property tests are not very strong (in my opinion) and some are very weak (there are opened issues that should tackle that). Also, most of property tests in this issue should be moved to cardano-crypto (where they could have prevented the unforseen bug). The actual surface for mistake is very small within this issue (as most of heavy lifting is done by cardano-crypto) so implementing additional tests for this issue should not be considered as high priority (in my opinion). 

There are multiple issues opened that can improve upon this issue (see development plan for links)

**Comment by piotr-iohk** [comment]
Looks good to me :) Closing.
