### ISSUE TITLE
Setup Weeder on CI

### ISSUE THREAD

**Issue by Anviking** [input-output-hk/cardano-wallet-legacy#48]
# Description
[weeder: Detect dead code](http://hackage.haskell.org/package/weeder)

# Acceptance Criteria

- [ ] Weeder runs on the codebase, on CI.

# PR

| Number    | Base      |
| ---       | ---       |
| [][PR-1] | `develop` |

[PR-1]: https://github.com/input-output-hk/cardano-wallet/pull/

**Comment by KtorZ** [comment]
Duplicated by #1
