### ISSUE TITLE
TODO: Move or Remove Coupling Between faucet and cardano-wallet

### ISSUE THREAD

**Issue by commandodev** [input-output-hk/cardano-wallet-legacy#5]
# Context

<What is the issue that we are seeing that is motivating this decision or
change. Give any elements that help understanding where this issue comes from.
Leave no room for suggestions or implicit deduction.>

Faucet has a dependency on the wallet's servant client. It will need to be fixed to point at the code's new location. At the moment, `faucet` (and a couple of other packages) lives on `cardano-sl` whereas, they aren't so-to-speak part of the settlement layer.  This package may therefore be re-located in its own repository, or in a more appropriated one like https://github.com/input-output-hk/cardano-shell.

# Decision

<Give details about the architectural decision and what it is doing. Be
extensive: use schemas and references when possible. Do not hesitate to use
schemas and references when possible.>

FIXME: To be discussed with ops. 

# Acceptance Criteria

<Use standard vocabulary to describe requirement levels RFC-2119: Must-Should-May.
e.g.: The API _must_ support creation of wallets through a dedicated endpoint.>

FIXME: To be defined with ops.

# PR

| Number    | Base      |
| ---       | ---       |
| [][PR-1] | `develop` |

[PR-1]: https://github.com/input-output-hk/cardano-wallet/pull/ 

---

# Consequences

<To be completed in retrospective. What becomes easier or more difficult to do
because of this change.>

**Comment by KtorZ** [comment]
We won't. Decision was made to keep `cardano-sl` frozen and to evolve on new repositories for the new features.
