### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by Viking0x** [input-output-hk/cardano-wallet-legacy#58]
# Context

No spanish translation available

# Decision

I want to translate to spanish the Cardano wallet

# Acceptance Criteria

We are millions of people at world that speak spanish

# PR

| Number    | Base      |
| ---       | ---       |
| [][PR-1] | `develop` |

[PR-1]: https://github.com/input-output-hk/cardano-wallet/pull/ 

---

# Consequences

<To be completed in retrospective. What becomes easier or more difficult to do
because of this change.>

**Comment by KtorZ** [comment]
Hi @Viking0x, this is not the right place to consider translation. This is a wallet **backend** and it doesn't make sense for an API to be translated in many languages.
