### ISSUE TITLE
Define The Node Monitoring & Node Management API(s) 

### ISSUE THREAD

**Issue by commandodev** [input-output-hk/cardano-wallet-legacy#7]
# Context

<What is the issue that we are seeing that is motivating this decision or
change. Give any elements that help understanding where this issue comes from.
Leave no room for suggestions or implicit deduction.>

The wallet currently offers some basic monitoring of the node via the `/api/v1/node-info` and 
`/api/v1/node-settings`. Underneath, this piggy-backs on the Node State Adaptor
and the fact that the Wallet is ultimately a node. This includes:

- `syncProgress`: Syncing progression, in percentage.
- `blockchainHeight`: If known, the current blockchain height, in number of blocks.
- `localBlockchainHeight`: Local blockchain height, in number of blocks.
- `localTimeInformation`: Information about the clock on this node.
- `subscriptionStatus`: Is the node connected to the network and to what peers?
- `slotDuration`: Duration of a slot.
- `softwareInfo`: Various pieces of information about the current software.
- `projectVersion`: Current project's version.
- `gitRevision`: Git revision of this deployment.

# Decision

<Give details about the architectural decision and what it is doing. Be
extensive: use schemas and references when possible. Do not hesitate to use
schemas and references when possible.>

Strictly considering the wallet, these pieces of information are quite out-of-scope. 
They should instead be provided by a node itself and queried by clients directly from 
the underlying node. 
At the moment, the Wallet is used as a kind of proxy to relay these pieces of information,
but in order to properly decouple the Wallet from the node, we should look into moving this
API onto the node, with a possible redesign as we do it. 

In order to avoid breaking the API versioning contract, we will be required to support the Node API in the V1 of `cardano-wallet`.
The V2 of the wallet API will not need to support it.

Additionally, the Wallet also may require the `systemStart` to be available in
such API in order to compute a few things from it.

# Acceptance Criteria

<Use standard vocabulary to describe requirement levels RFC-2119: Must-Should-May.
e.g.: The API _must_ support creation of wallets through a dedicated endpoint.>

1. - [x] There _must_ be a Servant API representing the Node Monitoring & Management API
2. - [x] The type from #7.1 _must_ be convertible to Swagger
3. - [x] The type from #7.1 _should_ be defined outside of `cardano-wallet`, on `cardano-sl`.

# PR

| Number    | Base      |
| ---       | ---       |
| [cardano-sl#3788][PR-1] | `cardano-sl/develop` |

[PR-1]: https://github.com/input-output-hk/cardano-sl/pull/3788

---

# Retrospective

<To be completed in retrospective. What becomes easier or more difficult to do
because of this change.>

- [3788](https://github.com/input-output-hk/cardano-sl/pull/3788) -- This PR upstreamed everything that was needed to support the node API definition from both `wallet-new` and `cardano-node` packages into `lib`. This was a relatively straightforward "pull the string" modification, where I copied code and didn't stop until the compile errors went away.
- [3820](https://github.com/input-output-hk/cardano-sl/pull/3820) -- This PR implemented the node API handlers, upstreaming the code necessary for that. Same as above, but it was complicated by orphan instances making a bit of a snag.
- [3851](https://github.com/input-output-hk/cardano-sl/pull/3851) -- This PR acquired resources from the environment to satisfy the handlers. This PR took longer than expected, as digging for "where does this value come from" is really difficult in the current codebase.
- [3910 (not yet merged)](https://github.com/input-output-hk/cardano-sl/pull/3910) -- This PR implements JSend error compliance.

**Comment by parsonsmatt** [comment]
I don't have any objection to the current design of the node management/info/settings API. I suggest that the API remain the same for the initial port. 

Therefore, the definition is already complete, and only needs to be separated out.

Where should the new API definition go? Will the node also use `servant` etc to make porting easier, or is a different web library desirable?

**Comment by KtorZ** [comment]
I don't think moving away from servant is a good idea. We already know how to use it and it works fine. Besides, it gives us a few things for free (easy API testing, swagger specs, HTTP client etc..) 

For the package, it'd make sense to create a new package inside cardano-sl. I don't think this should import anything from the wallet so we'll have to "redefine" a few things. Though the node API is fairly simple (no pagination or filtering there).
 
On the long term, we might want to extract the API layer from the wallet and make it a more generic library (or several libraries) to favor code re-use. But we aren't there yet.

**Comment by KtorZ** [comment]
Done in #3788
