### ISSUE TITLE
(CI) Control that each API response returns a JSEnd compliant response.

### ISSUE THREAD

**Issue by KtorZ** [input-output-hk/cardano-wallet-legacy#79]
# Context

<What is the issue that we are seeing that is motivating this decision or
change. Give any elements that help understanding where this issue comes from.
Leave no room for suggestions or implicit deduction.>

As a follow-up for #77, it's clear that we aren't enforcing any particular response format for the API. Therefore, it is possible to simply declare an API response that would be inconsistent with others. This can be controlled quite easily through the API types constructed with Servant. 

# Decision

<Give details about the architectural decision and what it is doing. Be
extensive: use schemas and references when possible. Do not hesitate to use
schemas and references when possible.>

Add or extend a unit test which check that each endpoint of the API uses a jsend-compliant format.
A good place to host this test could be: https://github.com/input-output-hk/cardano-wallet/blob/develop/test/unit/API/SwaggerSpec.hs

# Acceptance Criteria

<Use standard vocabulary to describe requirement levels RFC-2119: Must-Should-May.
e.g.: The API _must_ support creation of wallets through a dedicated endpoint.>

1. - [ ] The API _must_ return only jsend-compliant responses

---

# PR

| Number    | Base      |
| ---       | ---       |
| [#185][PR-1] | `develop` |

[PR-1]: https://github.com/input-output-hk/cardano-wallet/pull/185

# Consequences

<To be completed in retrospective. What becomes easier or more difficult to do
because of this change.>

# QA

An implementation for this issue calls for a QuickCheck property over all response types. Servant's type-level programming allows us to do this for successful responses, but it won't suffice for error or failure responses.

# Development Plan

- Reuse the type-level code from `servant-swagger` to collect all response types into a list.
- Reuse the `props` function from `servant-swagger` to write a property for all response types.

**Comment by piotr-iohk** [comment]
@parsonsmatt - I have one question. Is there a reason for limiting the tests generation to 10 examples per test only? Why not default 100 (or maybe more)? :)
i.e. -> https://github.com/input-output-hk/cardano-wallet/pull/185#issuecomment-450697280

**Comment by parsonsmatt** [comment]
@piotr-iohk It's likely a performance thing. The more test cases, the more time the test takes to run. With 10 examples per test, it takes 2.2876s to run the Swagger schema tests. With 100 examples, it takes 25.881s to run.

It'd probably be wise to have the test case generation for local development smaller and the CI runs (or perhaps just the nightly tests) to be significantly larger.
