### ISSUE TITLE
Implement the API(s) on The Node's End

### ISSUE THREAD

**Issue by commandodev** [input-output-hk/cardano-wallet-legacy#8]
# Context

<What is the issue that we are seeing that is motivating this decision or
change. Give any elements that help understanding where this issue comes from.
Leave no room for suggestions or implicit deduction.>

See #7 

# Decision

<Give details about the architectural decision and what it is doing. Be
extensive: use schemas and references when possible. Do not hesitate to use
schemas and references when possible.>

We'll move most of the implementation logic related to the API onto the node and have the wallet re-use this (since the wallet uses `cardano-sl` as a library). 
No need to hook the handlers into a process / server at this stage.

# Acceptance Criteria

<Use standard vocabulary to describe requirement levels RFC-2119: Must-Should-May.
e.g.: The API _must_ support creation of wallets through a dedicated endpoint.>

1. - [x] Handlers corresponding to the API defined in #7.1 _must_ be implemented 
1. - [x] There _mustn't_ be any dependencies from `cardano-sl` -> `cardano-wallet` introduced in #8.1

# PR

| Number    | Base      |
| ---       | ---       |
| [cardano-sl#3820][PR-1] | `cardano-sl/develop` |
| [cardano-sl#3851][PR-2] | `cardano-sl/develop` |

[PR-1]: https://github.com/input-output-hk/cardano-sl/pull/3820
[PR-2]: https://github.com/input-output-hk/cardano-sl/pull/3851

---

# Consequences

<To be completed in retrospective. What becomes easier or more difficult to do
because of this change.>

- Turns out the Node already had an API that it's serving! We'll fold that into the node's API as well, and eventually we'll stop serving both of them.

**Comment by KtorZ** [comment]
Work started in https://github.com/input-output-hk/cardano-sl/pull/3788
