### ISSUE TITLE
Add `getNewBlocks` to diffusion layer and call it from dedicated wallet worker 

### ISSUE THREAD

**Issue by paweljakubas** [input-output-hk/cardano-wallet-legacy#84]
# Context

See https://github.com/input-output-hk/cardano-wallet/wiki/ApplyingBlocks-Rollback-After-Refactoring-Byron

# Decision

We want to add diffusion layer mediated way of getting blocks, at this stage in parallel to the existent mechanism in order to compare results 

# Acceptance Criteria

1. - [ ] API call, `getNewBlocks`, must be added to diffusion layer. It may take header and return all blocks on top of it, 
2. - [ ] Worker that calls the trusted node periodically for new blocks using diffusion layer must be added to the wallet.
3. - [ ] Respective legacy solution results and the new ones must be compared during integration tests (`Trace.Debug` like logs may be used)

---

# PR

| Number    | Base      |
| ---       | ---       |
| [][PR-1] | `develop` |

[PR-1]: https://github.com/input-output-hk/cardano-wallet/pull/ 

# Consequences

<To be completed in retrospective. What becomes easier or more difficult to do
because of this change.>

**Comment by KtorZ** [comment]
Included in #88
