### ISSUE TITLE
`applyBlocks` of BListener is used in tandem with diffusion layer mechanism of getting blocks

### ISSUE THREAD

**Issue by paweljakubas** [input-output-hk/cardano-wallet-legacy#86]
# Context

See https://github.com/input-output-hk/cardano-wallet/wiki/ApplyingBlocks-Rollback-After-Refactoring-Byron

# Decision

We want to the diffusion layer mediated way of getting blocks to be the only way of retrieving blocks and use `applyBlocks` of BListener to accommodate the result of it

# Acceptance Criteria

1. - [ ] `applyBlocks` of BListener should be reused and must be propelled by blocks retrieved from `getNewBlocks` of diffusion layer

---

# PR

| Number    | Base      |
| ---       | ---       |
| [][PR-1] | `develop` |

[PR-1]: https://github.com/input-output-hk/cardano-wallet/pull/ 

# Consequences

<To be completed in retrospective. What becomes easier or more difficult to do
because of this change.>

**Comment by KtorZ** [comment]
Included in #88
