### ISSUE TITLE
Integrate the Wallet to Use the Node's API

### ISSUE THREAD

**Issue by commandodev** [input-output-hk/cardano-wallet-legacy#9]
# Context

<What is the issue that we are seeing that is motivating this decision or
change. Give any elements that help understanding where this issue comes from.
Leave no room for suggestions or implicit deduction.>

In order to avoid breaking the API versioning contract, we are required to support the Node API in the V1 of cardano-wallet. The V2 of the wallet API will not need to support it.

# Decision

<Give details about the architectural decision and what it is doing. Be
extensive: use schemas and references when possible. Do not hesitate to use
schemas and references when possible.>

Since both APIs are identical, it is really straight-forward to use one to implement the other. Though, we want to make sure that calls go over the wire as-if the two processes were decoupled.

# Acceptance Criteria

<Use standard vocabulary to describe requirement levels RFC-2119: Must-Should-May.
e.g.: The API _must_ support creation of wallets through a dedicated endpoint.>

1. - [x] `cardano-wallet` backward-compatible node monitoring API _should_ solely rely on a Node's API and relay requests through HTTP(s) to the node
1. - [x] We _may_ define a Haskell client to easily talk to the Node API from `cardano-wallet`

# PR

| Number    | Base      |
| ---       | ---       |
| [#160][PR-1] | `develop` |
| [#196][PR-2] | `develop` |
| [#210][PR-3] | `develop` |

[PR-1]: https://github.com/input-output-hk/cardano-wallet/pull/160
[PR-2]: https://github.com/input-output-hk/cardano-wallet/pull/196
[PR-3]: https://github.com/input-output-hk/cardano-wallet/pull/210

---

# Consequences

<To be completed in retrospective. What becomes easier or more difficult to do
because of this change.>

# QA 

| Criteria | Coverage |
| ---      | ---      |
| 1.        | Manual verification that node-related endpoints delegate to the Node API. Integration tests have been written to ensure that the wallet can do this successfully        |
| 2. | The code for a node client was written, but in the `cardano-sl` repository. |

**Comment by piotr-iohk** [comment]
LGTM :)
@parsonsmatt, just want to make sure, those changes did not require any changes in the API doc?

**Comment by KtorZ** [comment]
@piotr-iohk 
No, these changes are rather invisible to the users. Things are happening "behind the scene" (the handlers gets implemented differently) but, the external API stays the same.
